apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log
  template:
    metadata:
      labels:
        app: log
    spec:
      containers:
        - name: log
          image: 366141533193.dkr.ecr.ap-southeast-1.amazonaws.com/log-service:prod
          ports:
            - containerPort: 80
          env:
            - name: SQS_URL
              value: http://elasticmq:9324
            - name: SQS_QUEUE
              value: http://elasticmq:9324/queue/log-queue
            - name: MONGODB_URI
              value: mongodb://mongodb:27017
---
apiVersion: v1
kind: Service
metadata:
  name: log-service
spec:
  selector:
    app: log
  ports:
    - port: 80
      targetPort: 80