apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticmq
  template:
    metadata:
      labels:
        app: elasticmq
    spec:
      containers:
        - name: elasticmq
          image: softwaremill/elasticmq
          ports:
            - containerPort: 9324
---
apiVersion: v1
kind: Service
metadata:
  name: elasticmq
spec:
  selector:
    app: elasticmq
  ports:
    - port: 9324
      targetPort: 9324