apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log
  template:
    metadata:
      labels:
        app: log
    spec:
      containers:
        - name: log
          image: log-service
          ports:
            - containerPort: 8000
          env:
            - name: SQS_URL
              value: http://elasticmq:9324
            - name: SQS_QUEUE
              value: http://elasticmq:9324/queue/log-queue
            - name: MONGODB_URI
              value: mongodb://mongodb:27017
