apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-worker
  template:
    metadata:
      labels:
        app: log-worker
    spec:
      containers:
        - name: log-worker
          image: log-worker
          ports:
            - containerPort: 80
          env:
            - name: SQS_URL
              value: http://elasticmq:9324
            - name: SQS_QUEUE
              value: http://elasticmq:9324/queue/log-queue
            - name: MONGODB_URI
              value: mongodb://mongodb:27017
            - name: CLICKHOUSE_HOST
              value: "clickhouse"
            - name: CLICKHOUSE_PORT
              value: "8123"
            - name: CLICKHOUSE_USER
              value: "myuser"
            - name: CLICKHOUSE_PASSWORD
              value: "mypassword"
            - name: CLICKHOUSE_DATABASE
              value: "default"
