apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenant-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tenant
  template:
    metadata:
      labels:
        app: tenant
    spec:
      containers:
        - name: tenant
          image: tenant-service
          ports:
            - containerPort: 80
          env:
            - name: MONGODB_URI
              value: "mongodb://mongodb:27017"
---
apiVersion: v1
kind: Service
metadata:
  name: tenant-service
spec:
  selector:
    app: tenant
  ports:
    - port: 80
      targetPort: 80